2016-08-21 00:25:09,382 [11] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2016-08-21 00:25:09,382 [13] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2016-08-21 00:25:09,382 [12] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2016-08-21 00:26:11,483 [9] ERROR LeaRun.DataAccess.DbHelper - 超时时间已到。超时时间已到，但是尚未从池中获取连接。出现这种情况可能是因为所有池连接均在使用，并且达到了最大池大小。
2016-08-21 00:26:13,274 [10] ERROR LeaRun.DataAccess.DbHelper - 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
2016-08-21 00:26:38,610 [10] ERROR LeaRun.DataAccess.DbHelper - 用户 'sa' 登录失败。
2016-08-21 00:26:38,610 [9] ERROR LeaRun.DataAccess.DbHelper - 用户 'sa' 登录失败。
2016-08-21 00:26:44,154 [8] ERROR LeaRun.DataAccess.DbHelper - 用户 'sa' 登录失败。
2016-08-21 00:29:02,609 [12] ERROR LeaRun.DataAccess.DbHelper - 列名 'Cholesterol' 无效。
列名 'ChineseDiagnosis' 无效。
列名 'WESTDiagnosis' 无效。
列名 'MedicalRecord' 无效。
列名 'ConditionRecommand' 无效。
列名 'Other' 无效。
